// <auto-generated />
using System;
using DietHelper.Common.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DietHelper.Common.Migrations
{
    [DbContext(typeof(DietHelperDbContext))]
    [Migration("20251211140404_AddMultiUserSupport")]
    partial class AddMultiUserSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DietHelper.Common.Models.Dishes.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dishes", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("DietHelper.Common.Models.Dishes.DishIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DishId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("ProductId");

                    b.ToTable("DishIngredients", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("DietHelper.Common.Models.Dishes.UserDish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserDishes");
                });

            modelBuilder.Entity("DietHelper.Common.Models.Dishes.UserDishIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<int>("UserDishId")
                        .HasColumnType("integer");

                    b.Property<int>("UserProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserProductId");

                    b.HasIndex("UserDishId", "UserProductId")
                        .IsUnique();

                    b.ToTable("UserDishIngredients");
                });

            modelBuilder.Entity("DietHelper.Common.Models.Products.BaseProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("BaseProducts");
                });

            modelBuilder.Entity("DietHelper.Common.Models.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("DietHelper.Common.Models.Products.UserProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaseProductId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BaseProductId");

                    b.HasIndex("UserId", "BaseProductId")
                        .IsUnique();

                    b.ToTable("UserProducts");
                });

            modelBuilder.Entity("DietHelper.Common.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DietHelper.Common.Models.Dishes.Dish", b =>
                {
                    b.OwnsOne("DietHelper.Common.Models.Core.NutritionInfo", "NutritionFacts", b1 =>
                        {
                            b1.Property<int>("DishId")
                                .HasColumnType("integer");

                            b1.Property<double>("Calories")
                                .HasColumnType("double precision")
                                .HasColumnName("Calories");

                            b1.Property<double>("Carbs")
                                .HasColumnType("double precision")
                                .HasColumnName("Carbs");

                            b1.Property<double>("Fat")
                                .HasColumnType("double precision")
                                .HasColumnName("Fat");

                            b1.Property<double>("Protein")
                                .HasColumnType("double precision")
                                .HasColumnName("Protein");

                            b1.HasKey("DishId");

                            b1.ToTable("Dishes");

                            b1.WithOwner()
                                .HasForeignKey("DishId");
                        });

                    b.Navigation("NutritionFacts")
                        .IsRequired();
                });

            modelBuilder.Entity("DietHelper.Common.Models.Dishes.DishIngredient", b =>
                {
                    b.HasOne("DietHelper.Common.Models.Dishes.Dish", "Dish")
                        .WithMany("Ingredients")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DietHelper.Common.Models.Products.Product", "Ingredient")
                        .WithMany("DishIngredients")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("DietHelper.Common.Models.Dishes.UserDish", b =>
                {
                    b.HasOne("DietHelper.Common.Models.User", "User")
                        .WithMany("Dishes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DietHelper.Common.Models.Core.NutritionInfo", "NutritionFacts", b1 =>
                        {
                            b1.Property<int>("UserDishId")
                                .HasColumnType("integer");

                            b1.Property<double>("Calories")
                                .HasColumnType("double precision")
                                .HasColumnName("Calories");

                            b1.Property<double>("Carbs")
                                .HasColumnType("double precision")
                                .HasColumnName("Carbs");

                            b1.Property<double>("Fat")
                                .HasColumnType("double precision")
                                .HasColumnName("Fat");

                            b1.Property<double>("Protein")
                                .HasColumnType("double precision")
                                .HasColumnName("Protein");

                            b1.HasKey("UserDishId");

                            b1.ToTable("UserDishes");

                            b1.WithOwner()
                                .HasForeignKey("UserDishId");
                        });

                    b.Navigation("NutritionFacts")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DietHelper.Common.Models.Dishes.UserDishIngredient", b =>
                {
                    b.HasOne("DietHelper.Common.Models.Dishes.UserDish", "UserDish")
                        .WithMany("Ingredients")
                        .HasForeignKey("UserDishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DietHelper.Common.Models.Products.UserProduct", "UserProduct")
                        .WithMany("DishIngredients")
                        .HasForeignKey("UserProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserDish");

                    b.Navigation("UserProduct");
                });

            modelBuilder.Entity("DietHelper.Common.Models.Products.BaseProduct", b =>
                {
                    b.OwnsOne("DietHelper.Common.Models.Core.NutritionInfo", "NutritionFacts", b1 =>
                        {
                            b1.Property<int>("BaseProductId")
                                .HasColumnType("integer");

                            b1.Property<double>("Calories")
                                .HasColumnType("double precision")
                                .HasColumnName("Calories");

                            b1.Property<double>("Carbs")
                                .HasColumnType("double precision")
                                .HasColumnName("Carbs");

                            b1.Property<double>("Fat")
                                .HasColumnType("double precision")
                                .HasColumnName("Fat");

                            b1.Property<double>("Protein")
                                .HasColumnType("double precision")
                                .HasColumnName("Protein");

                            b1.HasKey("BaseProductId");

                            b1.ToTable("BaseProducts");

                            b1.WithOwner()
                                .HasForeignKey("BaseProductId");
                        });

                    b.Navigation("NutritionFacts")
                        .IsRequired();
                });

            modelBuilder.Entity("DietHelper.Common.Models.Products.Product", b =>
                {
                    b.OwnsOne("DietHelper.Common.Models.Core.NutritionInfo", "NutritionFacts", b1 =>
                        {
                            b1.Property<int>("ProductId")
                                .HasColumnType("integer");

                            b1.Property<double>("Calories")
                                .HasColumnType("double precision")
                                .HasColumnName("Calories");

                            b1.Property<double>("Carbs")
                                .HasColumnType("double precision")
                                .HasColumnName("Carbs");

                            b1.Property<double>("Fat")
                                .HasColumnType("double precision")
                                .HasColumnName("Fat");

                            b1.Property<double>("Protein")
                                .HasColumnType("double precision")
                                .HasColumnName("Protein");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("NutritionFacts")
                        .IsRequired();
                });

            modelBuilder.Entity("DietHelper.Common.Models.Products.UserProduct", b =>
                {
                    b.HasOne("DietHelper.Common.Models.Products.BaseProduct", "BaseProduct")
                        .WithMany("UserProducts")
                        .HasForeignKey("BaseProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DietHelper.Common.Models.User", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DietHelper.Common.Models.Core.NutritionInfo", "CustomNutrition", b1 =>
                        {
                            b1.Property<int>("UserProductId")
                                .HasColumnType("integer");

                            b1.Property<double>("Calories")
                                .HasColumnType("double precision")
                                .HasColumnName("CustomCalories");

                            b1.Property<double>("Carbs")
                                .HasColumnType("double precision")
                                .HasColumnName("CustomCarbs");

                            b1.Property<double>("Fat")
                                .HasColumnType("double precision")
                                .HasColumnName("CustomFat");

                            b1.Property<double>("Protein")
                                .HasColumnType("double precision")
                                .HasColumnName("CustomProtein");

                            b1.HasKey("UserProductId");

                            b1.ToTable("UserProducts");

                            b1.WithOwner()
                                .HasForeignKey("UserProductId");
                        });

                    b.Navigation("BaseProduct");

                    b.Navigation("CustomNutrition")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DietHelper.Common.Models.Dishes.Dish", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("DietHelper.Common.Models.Dishes.UserDish", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("DietHelper.Common.Models.Products.BaseProduct", b =>
                {
                    b.Navigation("UserProducts");
                });

            modelBuilder.Entity("DietHelper.Common.Models.Products.Product", b =>
                {
                    b.Navigation("DishIngredients");
                });

            modelBuilder.Entity("DietHelper.Common.Models.Products.UserProduct", b =>
                {
                    b.Navigation("DishIngredients");
                });

            modelBuilder.Entity("DietHelper.Common.Models.User", b =>
                {
                    b.Navigation("Dishes");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
