// <auto-generated />
using System;
using DietHelper.Common.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DietHelper.Common.Migrations
{
    [DbContext(typeof(DietHelperDbContext))]
    [Migration("20260217130601_AddHistory")]
    partial class AddHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DietHelper.Common.Models.Dishes.UserDish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReadyDish")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserDishes");
                });

            modelBuilder.Entity("DietHelper.Common.Models.Dishes.UserDishIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<int>("UserDishId")
                        .HasColumnType("integer");

                    b.Property<int>("UserProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserProductId");

                    b.HasIndex("UserDishId", "UserProductId")
                        .IsUnique();

                    b.ToTable("UserDishIngredients");
                });

            modelBuilder.Entity("DietHelper.Common.Models.MealEntries.UserMealEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("TotalQuantity")
                        .HasColumnType("numeric");

                    b.Property<int?>("UserDishId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserDishId");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("UserMealEntries");
                });

            modelBuilder.Entity("DietHelper.Common.Models.MealEntries.UserMealEntryIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ProductNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<int>("UserMealEntryId")
                        .HasColumnType("integer");

                    b.Property<int>("UserProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserMealEntryId");

                    b.HasIndex("UserProductId");

                    b.ToTable("UserMealEntryIngredients");
                });

            modelBuilder.Entity("DietHelper.Common.Models.Products.BaseProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("BaseProducts");
                });

            modelBuilder.Entity("DietHelper.Common.Models.Products.UserProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaseProductId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BaseProductId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "BaseProductId")
                        .IsUnique();

                    b.ToTable("UserProducts");
                });

            modelBuilder.Entity("DietHelper.Common.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("DietHelper.Common.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DietHelper.Common.Models.Dishes.UserDish", b =>
                {
                    b.HasOne("DietHelper.Common.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DietHelper.Common.Models.Core.NutritionInfo", "NutritionFacts", b1 =>
                        {
                            b1.Property<int>("UserDishId")
                                .HasColumnType("integer");

                            b1.Property<double>("Calories")
                                .HasColumnType("double precision")
                                .HasColumnName("Calories");

                            b1.Property<double>("Carbs")
                                .HasColumnType("double precision")
                                .HasColumnName("Carbs");

                            b1.Property<double>("Fat")
                                .HasColumnType("double precision")
                                .HasColumnName("Fat");

                            b1.Property<double>("Protein")
                                .HasColumnType("double precision")
                                .HasColumnName("Protein");

                            b1.HasKey("UserDishId");

                            b1.ToTable("UserDishes");

                            b1.WithOwner()
                                .HasForeignKey("UserDishId");
                        });

                    b.Navigation("NutritionFacts")
                        .IsRequired();
                });

            modelBuilder.Entity("DietHelper.Common.Models.Dishes.UserDishIngredient", b =>
                {
                    b.HasOne("DietHelper.Common.Models.Dishes.UserDish", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("UserDishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DietHelper.Common.Models.Products.UserProduct", "UserProduct")
                        .WithMany()
                        .HasForeignKey("UserProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("DietHelper.Common.Models.Core.NutritionInfo", "CurrentNutrition", b1 =>
                        {
                            b1.Property<int>("UserDishIngredientId")
                                .HasColumnType("integer");

                            b1.Property<double>("Calories")
                                .HasColumnType("double precision")
                                .HasColumnName("Calories");

                            b1.Property<double>("Carbs")
                                .HasColumnType("double precision")
                                .HasColumnName("Carbs");

                            b1.Property<double>("Fat")
                                .HasColumnType("double precision")
                                .HasColumnName("Fat");

                            b1.Property<double>("Protein")
                                .HasColumnType("double precision")
                                .HasColumnName("Protein");

                            b1.HasKey("UserDishIngredientId");

                            b1.ToTable("UserDishIngredients");

                            b1.WithOwner()
                                .HasForeignKey("UserDishIngredientId");
                        });

                    b.Navigation("CurrentNutrition")
                        .IsRequired();

                    b.Navigation("UserProduct");
                });

            modelBuilder.Entity("DietHelper.Common.Models.MealEntries.UserMealEntry", b =>
                {
                    b.HasOne("DietHelper.Common.Models.Dishes.UserDish", "UserDish")
                        .WithMany()
                        .HasForeignKey("UserDishId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DietHelper.Common.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DietHelper.Common.Models.Core.NutritionInfo", "TotalNutrition", b1 =>
                        {
                            b1.Property<int>("UserMealEntryId")
                                .HasColumnType("integer");

                            b1.Property<double>("Calories")
                                .HasColumnType("double precision")
                                .HasColumnName("TotalCalories");

                            b1.Property<double>("Carbs")
                                .HasColumnType("double precision")
                                .HasColumnName("TotalCarbs");

                            b1.Property<double>("Fat")
                                .HasColumnType("double precision")
                                .HasColumnName("TotalFat");

                            b1.Property<double>("Protein")
                                .HasColumnType("double precision")
                                .HasColumnName("TotalProtein");

                            b1.HasKey("UserMealEntryId");

                            b1.ToTable("UserMealEntries");

                            b1.WithOwner()
                                .HasForeignKey("UserMealEntryId");
                        });

                    b.Navigation("TotalNutrition")
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserDish");
                });

            modelBuilder.Entity("DietHelper.Common.Models.MealEntries.UserMealEntryIngredient", b =>
                {
                    b.HasOne("DietHelper.Common.Models.MealEntries.UserMealEntry", "UserMealEntry")
                        .WithMany("Ingredients")
                        .HasForeignKey("UserMealEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DietHelper.Common.Models.Products.UserProduct", "UserProduct")
                        .WithMany()
                        .HasForeignKey("UserProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("DietHelper.Common.Models.Core.NutritionInfo", "ProductNutritionInfoSnapshot", b1 =>
                        {
                            b1.Property<int>("UserMealEntryIngredientId")
                                .HasColumnType("integer");

                            b1.Property<double>("Calories")
                                .HasColumnType("double precision")
                                .HasColumnName("CaloriesSnapshot");

                            b1.Property<double>("Carbs")
                                .HasColumnType("double precision")
                                .HasColumnName("CarbsSnapshot");

                            b1.Property<double>("Fat")
                                .HasColumnType("double precision")
                                .HasColumnName("FatSnapshot");

                            b1.Property<double>("Protein")
                                .HasColumnType("double precision")
                                .HasColumnName("ProteinSnapshot");

                            b1.HasKey("UserMealEntryIngredientId");

                            b1.ToTable("UserMealEntryIngredients");

                            b1.WithOwner()
                                .HasForeignKey("UserMealEntryIngredientId");
                        });

                    b.Navigation("ProductNutritionInfoSnapshot")
                        .IsRequired();

                    b.Navigation("UserMealEntry");

                    b.Navigation("UserProduct");
                });

            modelBuilder.Entity("DietHelper.Common.Models.Products.BaseProduct", b =>
                {
                    b.OwnsOne("DietHelper.Common.Models.Core.NutritionInfo", "NutritionFacts", b1 =>
                        {
                            b1.Property<int>("BaseProductId")
                                .HasColumnType("integer");

                            b1.Property<double>("Calories")
                                .HasColumnType("double precision")
                                .HasColumnName("Calories");

                            b1.Property<double>("Carbs")
                                .HasColumnType("double precision")
                                .HasColumnName("Carbs");

                            b1.Property<double>("Fat")
                                .HasColumnType("double precision")
                                .HasColumnName("Fat");

                            b1.Property<double>("Protein")
                                .HasColumnType("double precision")
                                .HasColumnName("Protein");

                            b1.HasKey("BaseProductId");

                            b1.ToTable("BaseProducts");

                            b1.WithOwner()
                                .HasForeignKey("BaseProductId");
                        });

                    b.Navigation("NutritionFacts")
                        .IsRequired();
                });

            modelBuilder.Entity("DietHelper.Common.Models.Products.UserProduct", b =>
                {
                    b.HasOne("DietHelper.Common.Models.Products.BaseProduct", "BaseProduct")
                        .WithMany()
                        .HasForeignKey("BaseProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DietHelper.Common.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DietHelper.Common.Models.Core.NutritionInfo", "CustomNutrition", b1 =>
                        {
                            b1.Property<int>("UserProductId")
                                .HasColumnType("integer");

                            b1.Property<double>("Calories")
                                .HasColumnType("double precision")
                                .HasColumnName("CustomCalories");

                            b1.Property<double>("Carbs")
                                .HasColumnType("double precision")
                                .HasColumnName("CustomCarbs");

                            b1.Property<double>("Fat")
                                .HasColumnType("double precision")
                                .HasColumnName("CustomFat");

                            b1.Property<double>("Protein")
                                .HasColumnType("double precision")
                                .HasColumnName("CustomProtein");

                            b1.HasKey("UserProductId");

                            b1.ToTable("UserProducts");

                            b1.WithOwner()
                                .HasForeignKey("UserProductId");
                        });

                    b.Navigation("BaseProduct");

                    b.Navigation("CustomNutrition")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DietHelper.Common.Models.RefreshToken", b =>
                {
                    b.HasOne("DietHelper.Common.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("DietHelper.Common.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("DietHelper.Common.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DietHelper.Common.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("DietHelper.Common.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DietHelper.Common.Models.Dishes.UserDish", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("DietHelper.Common.Models.MealEntries.UserMealEntry", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
